### ISSUE TITLE
Cannot tap vetmeduni/hombrew-popgen

### ISSUE THREAD

**Issue by magicDGS** [vetmeduni/homebrew-popgen#39]
While running `brew tap vetmeduni/homebrew-popgen`, this errors/warnings are detected:

```
==> Tapping vetmeduni/popgen
Cloning into '/usr/local/Homebrew/Library/Taps/vetmeduni/homebrew-popgen'...
remote: Counting objects: 36, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 36 (delta 2), reused 25 (delta 0), pack-reused 0
Unpacking objects: 100% (36/36), done.
Error: Non-file alias: /usr/local/Homebrew/Library/Taps/vetmeduni/homebrew-popgen/Aliases/vcflib@1.0.0
Warning: Calling 'depends_on :perl' is deprecated!
Use 'depends_on "perl"' instead.
/usr/local/Homebrew/Library/Taps/vetmeduni/homebrew-popgen/Formula/popoolation2.rb:14:in `<class:Popoolation2>'
Please report this to the vetmeduni/popgen tap!

Warning: Calling 'depends_on :perl' is deprecated!
Use 'depends_on "perl"' instead.
/usr/local/Homebrew/Library/Taps/vetmeduni/homebrew-popgen/Formula/stacks.rb:18:in `<class:Stacks>'
Please report this to the vetmeduni/popgen tap!

Warning: Calling 'depends_on :mysql' is deprecated!
Use 'depends_on "mysql"' instead.
/usr/local/Homebrew/Library/Taps/vetmeduni/homebrew-popgen/Formula/stacks.rb:19:in `<class:Stacks>'
Please report this to the vetmeduni/popgen tap!

Error: Cannot tap vetmeduni/popgen: invalid syntax in tap!
```

**Comment by robmaz** [comment]
I think I deleted the vcflib.rb, but forgot the alias. Sorry!

**Comment by magicDGS** [comment]
I open #43 for stack warnings...
