### ISSUE TITLE
Stacks warning when brew tap

### ISSUE THREAD

**Issue by magicDGS** [vetmeduni/homebrew-popgen#43]
```
==> Tapping vetmeduni/popgen
Cloning into '/usr/local/Homebrew/Library/Taps/vetmeduni/homebrew-popgen'...
7000001remote: Counting objects: 36, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 36 (delta 2), reused 26 (delta 0), pack-reused 0
Unpacking objects: 100% (36/36), done.
Warning: Calling 'depends_on :perl' is deprecated!
Use 'depends_on "perl"' instead.
/usr/local/Homebrew/Library/Taps/vetmeduni/homebrew-popgen/Formula/stacks.rb:18:in `<class:Stacks>'
Please report this to the vetmeduni/popgen tap!

Warning: Calling 'depends_on :mysql' is deprecated!
Use 'depends_on "mysql"' instead.
/usr/local/Homebrew/Library/Taps/vetmeduni/homebrew-popgen/Formula/stacks.rb:19:in `<class:Stacks>'
Please report this to the vetmeduni/popgen tap!

Tapped 17 formulae (89 files, 76.0KB)
```

**Comment by robmaz** [comment]
Stacks is no longer in our repo.
